<div style="text-align: center; padding: 40px; background-color: #102a43; border-radius: 15px; border: 2px solid #243b53; box-shadow: 0 10px 20px rgba(0,0,0,0.2);">
    <h1 style="color: #ffffff; font-family: 'Arial', sans-serif; font-size: 42px; margin-bottom: 5px;">𝑷𝒂𝒏𝒅𝒂𝒔 𝑺𝒕𝒓𝒊𝒏𝒈 𝑴𝒆𝒕𝒉𝒐𝒅𝒔</h1>
    <h3 style="color: #9fb3c8; font-family: 'Arial', sans-serif; font-size: 24px; margin-top: 0;">𝑾𝒐𝒓𝒌𝒊𝒏𝒈 𝒘𝒊𝒕𝒉 𝑻𝒆𝒙𝒕 𝑫𝒂𝒕𝒂</h3>
    <hr style="width: 60%; border: 0.5px solid #486581; margin: 25px auto;">
    <p style="color: #ffffff; font-size: 22px; margin-bottom: 5px;">Created by: <span style="color: #33adff; font-weight: bold;">Muhammad Adnan</span></p>
    <p style="color: #9fb3c8; font-size: 14px; letter-spacing: 2px; text-transform: uppercase;">Data Cleaning • Pandas • Text Processing</p>
</div>

<div style="padding: 30px; background-color: #1e293b; border-radius: 15px; border: 2px solid #334155; margin-top: 20px; box-shadow: 0 6px 15px rgba(0,0,0,0.2);">
<h2 style="color: #facc15; font-size: 26px;">About This Notebook</h2>
<p style="color: #e2e8f0; font-size: 16px; line-height: 1.6;">This notebook shows how Pandas applies <b>vectorized string operations</b> through the <code>.str</code> accessor, using the Titanic passenger names as a real-world example.</p>
<h3 style="color: #facc15; font-size: 22px;">Objective</h3>
<p style="color: #e2e8f0; font-size: 16px; line-height: 1.6;">To learn how to clean, split, filter and transform text columns quickly and safely, including missing values.</p>
<h3 style="color: #facc15; font-size: 22px;">Topics Covered</h3>
<ul style="color: #e2e8f0; font-size: 16px; line-height: 1.8;">
<li>Vectorized operations and why <code>.str</code> exists</li>
<li>Common string functions (case, length, strip)</li>
<li>Splitting names into surname, title and first name</li>
<li>Replacing values and filtering with <code>startswith</code> / <code>endswith</code></li>
<li>Regex with <code>contains</code> and slicing strings</li>
</ul>
</div>

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Imports
</div>

In [4]:
import pandas as pd
import numpy as np

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Why String Methods in Pandas? (Vectorized Operations)
</div>

In [5]:
# What are vectorized operations
a = np.array([1,2,3,4])
a * 4

array([ 4,  8, 12, 16])

In [ ]:
# problem in vectorized opertions in vanilla python
s = ['cat','mat',None,'rat']

[i.startswith('c') for i in s]

In [6]:
# How pandas solves this issue?

s = pd.Series(['cat','mat',None,'rat'])
# string accessor
s.str.startswith('c')

# fast and optimized

0     True
1    False
2     None
3    False
dtype: object

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Load the Titanic Dataset
</div>

In [ ]:
# import titanic
df = pd.read_csv('../data/titanic.csv')
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Common String Functions
</div>

In [ ]:
# Common Functions
# lower/upper/capitalize/title
df['Name'].str.upper()
df['Name'].str.capitalize()
df['Name'].str.title()
# len
df['Name'][df['Name'].str.len() == 82].values[0]
# strip
"                   nitish                              ".strip()
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Splitting Strings
</div>

In [ ]:
# split -> get
df['lastname'] = df['Name'].str.split(',').str.get(0)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen

In [ ]:
df[['title','firstname']] = df['Name'].str.split(',').str.get(1).str.strip().str.split(' ', n=1, expand=True)
df.head()

df['title'].value_counts()

Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Mlle.          2
Major.         2
Col.           2
the            1
Capt.          1
Ms.            1
Sir.           1
Lady.          1
Mme.           1
Don.           1
Jonkheer.      1
Name: title, dtype: int64

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Replacing Values
</div>

In [ ]:
# replace
df['title'] = df['title'].str.replace('Ms.','Miss.')
df['title'] = df['title'].str.replace('Mlle.','Miss.')

<ipython-input-60-9403e5934d1f>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['title'] = df['title'].str.replace('Ms.','Miss.')
<ipython-input-60-9403e5934d1f>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df['title'] = df['title'].str.replace('Mlle.','Miss.')

In [ ]:
df['title'].value_counts()

Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Mme.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: title, dtype: int64

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Filtering with String Methods
</div>

In [ ]:
# filtering
# startswith/endswith
df[df['firstname'].str.endswith('A')]
# isdigit/isalpha...
df[df['firstname'].str.isdigit()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, lastname, title, firstname]
Index: []

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Regex Operations
</div>

In [ ]:
# applying regex
# contains
# search john -> both case
df[df['firstname'].str.contains('john',case=False)]
# find lastnames with start and end char vowel
df[df['lastname'].str.contains('^[^aeiouAEIOU].+[^aeiouAEIOU]$')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,title,firstname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Moran,Mr.,James
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,McCarthy,Mr.,Timothy J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,Sutehall,Mr.,Henry Jr
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret Edith
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Johnston,Miss.,"Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl Howell
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr.,Patrick

<div style="font-size: 25px; font-weight: bold; color: #33adff; text-align: left; margin-top: 20px;">
Slicing Strings
</div>

In [ ]:
# slicing
df['Name'].str[::-1]

0                                sirraH newO .rM ,dnuarB
1      )reyahT sggirB ecnerolF( yeldarB nhoJ .srM ,sg...
2                                 aniaL .ssiM ,nenikkieH
3           )leeP yaM yliL( htaeH seuqcaJ .srM ,ellertuF
4                               yrneH mailliW .rM ,nellA
                             ...
886                                sazouJ .veR ,alivtnoM
887                         htidE teragraM .ssiM ,maharG
888             "eirraC" neleH enirehtaC .ssiM ,notsnhoJ
889                                llewoH lraK .rM ,rheB
890                                  kcirtaP .rM ,yelooD
Name: Name, Length: 891, dtype: object